### ISSUE TITLE
failed to compile a simple CUDA program

### ISSUE THREAD

**Issue by haoweiliang1996** [davisking/dlib#1365]
failed to compile a simple CUDA program
## Expected Behavior

 i want to use coda to speed cnn face detect but i failed to compile a simple CUDA program
## Current Behavior
-- Found CUDA: /usr/local/cuda-9.0 (found suitable version "9.0", minimum required is "7.5")
-- Looking for cuDNN install...
-- Found cuDNN: /usr/local/cuda-9.0/lib64/libcudnn.so
-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- *****************************************************************************************************************
-- *** CUDA was found but your compiler failed to compile a simple CUDA program so dlib isn't going to use CUDA.
-- *** The output of the failed CUDA test compile is shown below:
-- ***   Change Dir: /home/lhw/dlib/dlib-19.13.1/build/temp.linux-x86_64-3.6/dlib_build/cuda_test_build
   ***
   ***   Run Build Command:"/usr/bin/make"
   ***   [ 50%] Building NVCC (Device) object CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o
   ***   /usr/include/c++/5/functional(78): error: class "std::thread" has no member "result_type"
   ***             detected during:
   ***               instantiation of class "std::_Maybe_get_result_type<_Functor, void> [with _Functor=std::thread]"
   ***   (86): here
   ***               instantiation of class "std::_Weak_result_type_impl<_Functor> [with _Functor=std::thread]"
   ***   (184): here
   ***               instantiation of class "std::_Weak_result_type<_Functor> [with _Functor=std::thread]"
   ***   (264): here
   ***               instantiation of class "std::_Reference_wrapper_base_impl<true, true, _Tp> [with _Tp=std::thread]"
   ***   (283): here
   ***               instantiation of class "std::_Reference_wrapper_base<_Tp> [with _Tp=std::thread]"
   ***   (399): here
   ***               instantiation of class "std::reference_wrapper<_Tp> [with _Tp=std::thread]"
   ***   /usr/include/c++/5/future(1638): here
   ***
   ***   /usr/include/c++/5/functional(266): error: class "std::thread" has no member "argument_type"
   ***             detected during:
   ***               instantiation of class "std::_Reference_wrapper_base_impl<true, true, _Tp> [with _Tp=std::thread]"
   ***   (283): here
   ***               instantiation of class "std::_Reference_wrapper_base<_Tp> [with _Tp=std::thread]"
   ***   (399): here
   ***               instantiation of class "std::reference_wrapper<_Tp> [with _Tp=std::thread]"
   ***   /usr/include/c++/5/future(1638): here
   ***
   ***   /usr/include/c++/5/functional(267): error: class "std::thread" has no member "first_argument_type"
   ***             detected during:
   ***               instantiation of class "std::_Reference_wrapper_base_impl<true, true, _Tp> [with _Tp=std::thread]"
   ***   (283): here
   ***               instantiation of class "std::_Reference_wrapper_base<_Tp> [with _Tp=std::thread]"
   ***   (399): here
   ***               instantiation of class "std::reference_wrapper<_Tp> [with _Tp=std::thread]"
   ***   /usr/include/c++/5/future(1638): here
   ***
   ***   /usr/include/c++/5/functional(268): error: class "std::thread" has no member "second_argument_type"
   ***             detected during:
   ***               instantiation of class "std::_Reference_wrapper_base_impl<true, true, _Tp> [with _Tp=std::thread]"
   ***   (283): here
   ***               instantiation of class "std::_Reference_wrapper_base<_Tp> [with _Tp=std::thread]"
   ***   (399): here
   ***               instantiation of class "std::reference_wrapper<_Tp> [with _Tp=std::thread]"
   ***   /usr/include/c++/5/future(1638): here
   ***
   ***   4 errors detected in the compilation of "/tmp/tmpxft_0000fd33_00000000-7_cuda_test.cpp1.ii".
   ***   CMake Error at cuda_test_generated_cuda_test.cu.o.cmake:262 (message):
   ***     Error generating file
   ***     /home/lhw/dlib/dlib-19.13.1/build/temp.linux-x86_64-3.6/dlib_build/cuda_test_build/CMakeFiles/cuda_test.dir//./cuda_test_generated_cuda_test.cu.o
   ***
   ***
   ***   CMakeFiles/cuda_test.dir/build.make:63: recipe for target 'CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o' failed
   ***   make[2]: *** [CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o] Error 1
   ***   CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cuda_test.dir/all' failed
   ***   make[1]: *** [CMakeFiles/cuda_test.dir/all] Error 2
   ***   Makefile:83: recipe for target 'all' failed
   ***   make: *** [all] Error 2
   ***
-- *****************************************************************************************************************
-- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
## Steps to Reproduce

* **Version**: 19.13.1
* **Where did you get dlib**: pip download dlib
* **Platform**: ubuntu 16.04 64bit
* **Compiler**: The C compiler identification is GNU 5.4.0,The CXX compiler identification is GNU 5.4.0

**Comment by rjeli** [comment]
I fixed this by using gcc-6 instead of gcc-5. make sure your cuda version is recent enough to support it. (for me, 9.0 works)

**Comment by AeroClassics** [comment]
I had a similar problem in Ubuntu 18.04. Here are the steps I used to solve it:

1. cd to the dLib build directory
2. rm -rf *
3. cmake … (this fails on the CUDA test file so no CUDA support)
4. rm -rf *
5. cmake … -DCUDA_HOST_COMPILER=/usr/bin/gcc-6 (Now I have CUDA support)
6. cmake --build . --config Release
7. sudo ldconfig
8. cd …
9. python3 setup.py install (fails on CUDA test program, no cuda support)
10. I forgot to enable my python env
11. workon cv
12. python3 setup.py install (fails on Cuda Test program, no CUDA support)
13. python3 setup.py --compiler-flags “-DCUDA_HOST_COMPILER=usr/bin/gcc-6” install (no failures, but does not say CUDA support so I am assuming I have it)

Doug

**Comment by davisking** [comment]
You have cuda support if dlib.DLIB_USE_CUDA is true.  

Also, running cmake and ldconfig are not required when using the python API.  In fact, those steps do nothing at all related to using dlib in python.   I keep seeing people post these instructions all over the place.  I assume you read them somewhere? Can you tell me where?

**Comment by AeroClassics** [comment]
Hi Davis,
I saw that in a blog that you responded to saying it was not necessary. I have followed so many different blogs it is hard to get them down but here goes:
https://www.learnopencv.com/install-dlib-on-ubuntu/
https://peshmerge.io/how-to-build-dlib-on-linux-ubuntu-18-04-using-cmake-with-avx-support-and-install-its-python-api/

Are two. I usually follow what Satya Mallick and Adrian Rosebrock suggest as I am taking both courses. I put in a report on the dlib web site. It is less of a report and more of how I got around the problems I was seeing. Here is what I ended up doing:

I will post the whole thing in answer to your next email.

Best Regards / Mit freundlichen Grüßen,
Doug



[cid:image001.png@01D3D5F5.7EE2C150]

Douglas R. Jones
Sr. Software Engineer/AdVISE Project Mgr.
Rohde & Schwarz USA, Inc.
1500 Lakeside Parkway Ste 100
Flower Mound, TX 75028
Mobile: +1 214-601-3301
Office: +1 469-713-5344
E-Mail: Doug.Jones@rsa.rohde-schwarz.com<mailto:Doug.Jones@rsa.rohde-schwarz.com>
Website: http://www.rohde-schwarz.com/

**Comment by davisking** [comment]
Ok.  Thanks for reporting this.

The official instructions are here: http://dlib.net/compile.html.  Did you see them?  Somehow I get the impression that many users don't find that page.  Or they ignore it.

**Comment by AeroClassics** [comment]
Hi,
Yes, I did. But after being away from Linux/Unix for 10 years I just followed what Adreian and Satya suggest.

Best Regards / Mit freundlichen Grüßen,
Doug



[cid:image001.png@01D3D5F5.7EE2C150]

Douglas R. Jones
Sr. Software Engineer/AdVISE Project Mgr.
Rohde & Schwarz USA, Inc.
1500 Lakeside Parkway Ste 100
Flower Mound, TX 75028
Mobile: +1 214-601-3301
Office: +1 469-713-5344
E-Mail: Doug.Jones@rsa.rohde-schwarz.com<mailto:Doug.Jones@rsa.rohde-schwarz.com>
Website: http://www.rohde-schwarz.com/

**Comment by lamergameryt** [comment]
I know this issue is closed, but I encountered this issue after installing CUDA and cuDNN (Ubuntu 22.04). I couldn't get dlib to work with CUDA support as I met the error: `CUDA was found but your compiler failed to compile a simple CUDA program so dlib isn't going to use CUDA.`

I solved this issue by installing GCC 6 and G++ 6 and using the command `python3 setup.py --set CUDA_HOST_COMPILER=/usr/bin/gcc-6 install` after cleaning the build directory. After doing the above steps, I successfully compiled dlib with CUDA and received `Enabling CUDA support for dlib.  DLIB WILL USE CUDA`
