### ISSUE TITLE
Fail to compile dlib with cuda 10.1

### ISSUE THREAD

**Issue by daisyron** [davisking/dlib#1676]
Hi,

Tried to compile dlib 19.16 with cuda 10.1, and got the following error during running cmake:

-- Found CUDA: /usr/local/cuda (found suitable version "10.1", minimum required is "7.5") 
-- Looking for cuDNN install...
-- Found cuDNN: /usr/local/cuda/lib64/libcudnn.so
-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- *****************************************************************************************************************
-- *** CUDA was found but your compiler failed to compile a simple CUDA program so dlib isn't going to use CUDA. 
-- *** The output of the failed CUDA test compile is shown below: 
-- ***   Change Dir: /home/ron/DeepLearning/dlib-19.16/build/dlib/cuda_test_build
   ***   
   ***   Run Build Command:"/usr/bin/gmake"
   ***   [ 50%] Building NVCC (Device) object CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o
   ***   /home/ron/DeepLearning/dlib-19.16/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h: In instantiation of ‘dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::literal_assign_helper::~literal_assign_helper() [with T = double; long int num_rows = 2; long int num_cols = 2; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’:
   ***   /home/ron/DeepLearning/dlib-19.16/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/../optimization/optimization_line_search.h:209:11:   required from here
   ***   /home/ron/DeepLearning/dlib-19.16/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h:1774:36: error: cannot call member function ‘long int dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::nr() const [with T = double; long int num_rows = 2; long int num_cols = 2; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’ without object
   ***                    DLIB_CASSERT(!has_been_used || r == m->nr(),
   ***                                  ~~~~~^~~~~~~~
   ***   /home/ron/DeepLearning/dlib-19.16/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h: In instantiation of ‘const dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::literal_assign_helper& dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::literal_assign_helper::operator,(const T&) const [with T = double; long int num_rows = 2; long int num_cols = 2; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’:
   ***   /home/ron/DeepLearning/dlib-19.16/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/../optimization/optimization_line_search.h:209:23:   required from here
   ***   /home/ron/DeepLearning/dlib-19.16/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h:1783:14: error: cannot call member function ‘long int dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::nr() const [with T = double; long int num_rows = 2; long int num_cols = 2; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’ without object
   ***                    DLIB_CASSERT(r < m->nr() && c < m->nc(),
   ***                 ^  ~~~~
   ***   /home/ron/DeepLearning/dlib-19.16/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h:1783:30: error: cannot call member function ‘long int dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::nc() const [with T = double; long int num_rows = 2; long int num_cols = 2; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’ without object
   ***                    DLIB_CASSERT(r < m->nr() && c < m->nc(),
   ***                            ~~~~~^~~~~~~
   ***   /home/ron/DeepLearning/dlib-19.16/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h:1783:893: error: cannot call member function ‘long int dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::nr() const [with T = double; long int num_rows = 2; long int num_cols = 2; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’ without object
   ***                    DLIB_CASSERT(r < m->nr() && c < m->nc(),
   ***                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ^          
   ***   /home/ron/DeepLearning/dlib-19.16/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h:1783:929: error: cannot call member function ‘long int dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::nc() const [with T = double; long int num_rows = 2; long int num_cols = 2; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’ without object
   ***                    DLIB_CASSERT(r < m->nr() && c < m->nc(),
   ***                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ^          
   ***   /home/ron/DeepLearning/dlib-19.16/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h: In instantiation of ‘dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::literal_assign_helper::~literal_assign_helper() [with T = double; long int num_rows = 2; long int num_cols = 1; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’:
   ***   /home/ron/DeepLearning/dlib-19.16/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/../optimization/optimization_line_search.h:211:32:   required from here
   ***   /home/ron/DeepLearning/dlib-19.16/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h:1774:36: error: cannot call member function ‘long int dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::nr() const [with T = double; long int num_rows = 2; long int num_cols = 1; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’ without object
   ***                    DLIB_CASSERT(!has_been_used || r == m->nr(),
   ***                                  ~~~~~^~~~~~~~
   ***   /home/ron/DeepLearning/dlib-19.16/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h: In instantiation of ‘const dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::literal_assign_helper& dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::literal_assign_helper::operator,(const T&) const [with T = double; long int num_rows = 2; long int num_cols = 1; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’:
   ***   /home/ron/DeepLearning/dlib-19.16/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/../optimization/optimization_line_search.h:211:61:   required from here
   ***   /home/ron/DeepLearning/dlib-19.16/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h:1783:14: error: cannot call member function ‘long int dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::nr() const [with T = double; long int num_rows = 2; long int num_cols = 1; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’ without object
   ***                    DLIB_CASSERT(r < m->nr() && c < m->nc(),
   ***                 ^  ~~~~
   ***   /home/ron/DeepLearning/dlib-19.16/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h:1783:30: error: cannot call member function ‘long int dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::nc() const [with T = double; long int num_rows = 2; long int num_cols = 1; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’ without object
   ***                    DLIB_CASSERT(r < m->nr() && c < m->nc(),
   ***                            ~~~~~^~~~~~~
   ***   /home/ron/DeepLearning/dlib-19.16/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h:1783:893: error: cannot call member function ‘long int dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::nr() const [with T = double; long int num_rows = 2; long int num_cols = 1; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’ without object
   ***                    DLIB_CASSERT(r < m->nr() && c < m->nc(),
   ***                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ^          
   ***   /home/ron/DeepLearning/dlib-19.16/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h:1783:929: error: cannot call member function ‘long int dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::nc() const [with T = double; long int num_rows = 2; long int num_cols = 1; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’ without object
   ***                    DLIB_CASSERT(r < m->nr() && c < m->nc(),
   ***                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ^          
   ***   CMake Error at cuda_test_generated_cuda_test.cu.o.cmake:275 (message):
   ***     Error generating file
   ***     /home/ron/DeepLearning/dlib-19.16/build/dlib/cuda_test_build/CMakeFiles/cuda_test.dir//./cuda_test_generated_cuda_test.cu.o
   ***   
   ***   
   ***   gmake[2]: *** [CMakeFiles/cuda_test.dir/build.make:65: CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o] Error 1
   ***   gmake[1]: *** [CMakeFiles/Makefile2:72: CMakeFiles/cuda_test.dir/all] Error 2
   ***   gmake: *** [Makefile:84: all] Error 2
   ***   
-- *****************************************************************************************************************

Any comment?

Thanks.
Ron.

**Comment by yuaowang** [comment]
same error...

**Comment by davisking** [comment]
I just tried cuda 10.1 and the only issue I found was on some versions of cmake it doesn't find cusolver.  I just pushed a fix for that, but I didn't see any other issues.  There is probably just something wrong with your cuda install unrelated to dlib.

Make sure to follow the official cuda install steps on nvidia's website.  A lot of people complain about cuda being hard to install, but I never have any issues installing cuda on any platforms.  However, I ***never*** install it any other way than via the official install instructions.

**Comment by davisking** [comment]
Both of you need to fill out the issue template. I don't even know what systems you are trying to build on.  Maybe you are trying to use cuda on an OS NVIDIA doesn't support.  I have no idea.

**Comment by daisyron** [comment]
Hi,

Actually it seems that my cuda installation is OK - I can compile and run cuda programs I have without any issue.

The problem I described occurs in the cmake stage (cmake version 3.12.1), where he tries to compile a "simple" cuda program (with includes from dlib) - does it relate to the issue you found? 

My system configuration:

dlib version: 
  19.16
where from: 
  official download (from web site)
version: (Fedora 29, 'lsb_release -a'):
  LSB Version:	:core-4.1-amd64:core-4.1-noarch
  Distributor ID:	Fedora
  Description:	Fedora release 29 (Twenty Nine)
  Release:	29
Codename:	TwentyNine

Compiler:
  g++ (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)

CMAKE:
  cmake version 3.12.1


Thanks,
Ron.

**Comment by daisyron** [comment]
Update: Problem repeated also by taking the repository head (git clone).

**Comment by yuaowang** [comment]
Hi, thank you for your help.

Here is my system:

- Distributor ID:	Ubuntu
- Description:	Ubuntu 18.04.2 LTS
- Release:	18.04
- Codename:	bionic

- CMake version: 3.10.2

- dlib version: 19.16.0

- cuda version: cuda-10.1

- g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

Cheers,
Yuao

**Comment by davisking** [comment]
Go try and build the `dlib/cmake_utils/test_for_cuda` test project directly
and see what it says.

**Comment by daisyron** [comment]
Same results :-(

Actually the issue is related to initialization of 2x2 matrix at optimization_line_search.h:

        matrix<double,2,2> m;
        matrix<double,2,1> v;

        const double aa2 = x2*x2;
        const double aa1 = x1*x1;
        m =  aa2,       -aa1,
            -aa2*x2, aa1*x1;   
        v = f_x1 - f0 - d0*x1,
            f_x2 - f0 - d0*x2;

There is an issue initializing the m matrix...

Ron.

**Comment by alexmarkley** [comment]
<!-- Delete the above instructions and then provide a general summary of the issue in the Title above.  Then fill out the template below.  FAILURE TO FILL OUT EVERY PART WILL RESULT IN YOUR ISSUE BEING CLOSED -->

## Expected Behavior
<!--- Tell us what should happen.  What were you doing?  What part of dlib are you using?  What do you think should happen? -->
I expect dlib to compile successfully using CUDA 10.1

## Current Behavior
<!--- Tell us what happens instead of the expected behavior.  If you get an error, include the entire error message in the bug report.  DO NOT POST SCREEN SHOTS.  Paste in the text instead.   If the issue is some kind of build problem, include the entire CMake output along with the error message. -->
Cmake configuration fails with `CUDA was found but your compiler failed to compile a simple CUDA program so dlib isn't going to use CUDA.`

The error is the same as OP's, but I'm pasting it here for completeness.

```
-- The C compiler identification is GNU 8.3.1
-- The CXX compiler identification is GNU 8.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CMake version: 3.12.1
-- Compiling dlib version: 19.16.99
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Looking for png_create_read_struct
-- Looking for png_create_read_struct - found
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.5.3") 
-- Checking for module 'cblas'
--   Package 'cblas', required by 'virtual:world', not found
-- Checking for module 'lapack'
--   Package 'lapack', required by 'virtual:world', not found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Found OpenBLAS library
-- Looking for sgetrf_single
-- Looking for sgetrf_single - found
-- Using OpenBLAS's built in LAPACK
-- Looking for cblas_ddot
-- Looking for cblas_ddot - found
-- Looking for sgesv
-- Looking for sgesv - not found
-- Looking for sgesv_
-- Looking for sgesv_ - not found
-- Found CUDA: /usr/local/cuda (found suitable version "10.1", minimum required is "7.5") 
-- Looking for cuDNN install...
-- Found cuDNN: /usr/lib64/libcudnn.so
-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- *****************************************************************************************************************
-- *** CUDA was found but your compiler failed to compile a simple CUDA program so dlib isn't going to use CUDA. 
-- *** The output of the failed CUDA test compile is shown below: 
-- ***   Change Dir: /home/alex/Build/dlib/dlib_git/build/dlib/cuda_test_build
   ***   
   ***   Run Build Command:"/usr/bin/gmake"
   ***   [ 50%] Building NVCC (Device) object CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o
   ***   /home/alex/Build/dlib/dlib_git/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h: In instantiation of ‘dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::literal_assign_helper::~literal_assign_helper() [with T = double; long int num_rows = 2; long int num_cols = 2; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’:
   ***   /home/alex/Build/dlib/dlib_git/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/../optimization/optimization_line_search.h:209:11:   required from here
   ***   /home/alex/Build/dlib/dlib_git/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h:1774:36: error: cannot call member function ‘long int dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::nr() const [with T = double; long int num_rows = 2; long int num_cols = 2; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’ without object
   ***                    DLIB_CASSERT(!has_been_used || r == m->nr(),
   ***                                  ~~~~~^~~~~~~~
   ***   /home/alex/Build/dlib/dlib_git/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h: In instantiation of ‘const dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::literal_assign_helper& dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::literal_assign_helper::operator,(const T&) const [with T = double; long int num_rows = 2; long int num_cols = 2; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’:
   ***   /home/alex/Build/dlib/dlib_git/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/../optimization/optimization_line_search.h:209:23:   required from here
   ***   /home/alex/Build/dlib/dlib_git/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h:1783:14: error: cannot call member function ‘long int dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::nr() const [with T = double; long int num_rows = 2; long int num_cols = 2; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’ without object
   ***                    DLIB_CASSERT(r < m->nr() && c < m->nc(),
   ***                 ^  ~~~~
   ***   /home/alex/Build/dlib/dlib_git/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h:1783:30: error: cannot call member function ‘long int dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::nc() const [with T = double; long int num_rows = 2; long int num_cols = 2; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’ without object
   ***                    DLIB_CASSERT(r < m->nr() && c < m->nc(),
   ***                            ~~~~~^~~~~~~
   ***   /home/alex/Build/dlib/dlib_git/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h:1783:890: error: cannot call member function ‘long int dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::nr() const [with T = double; long int num_rows = 2; long int num_cols = 2; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’ without object
   ***                    DLIB_CASSERT(r < m->nr() && c < m->nc(),
   ***                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^          
   ***   /home/alex/Build/dlib/dlib_git/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h:1783:926: error: cannot call member function ‘long int dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::nc() const [with T = double; long int num_rows = 2; long int num_cols = 2; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’ without object
   ***                    DLIB_CASSERT(r < m->nr() && c < m->nc(),
   ***                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^          
   ***   /home/alex/Build/dlib/dlib_git/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h: In instantiation of ‘dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::literal_assign_helper::~literal_assign_helper() [with T = double; long int num_rows = 2; long int num_cols = 1; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’:
   ***   /home/alex/Build/dlib/dlib_git/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/../optimization/optimization_line_search.h:211:32:   required from here
   ***   /home/alex/Build/dlib/dlib_git/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h:1774:36: error: cannot call member function ‘long int dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::nr() const [with T = double; long int num_rows = 2; long int num_cols = 1; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’ without object
   ***                    DLIB_CASSERT(!has_been_used || r == m->nr(),
   ***                                  ~~~~~^~~~~~~~
   ***   /home/alex/Build/dlib/dlib_git/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h: In instantiation of ‘const dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::literal_assign_helper& dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::literal_assign_helper::operator,(const T&) const [with T = double; long int num_rows = 2; long int num_cols = 1; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’:
   ***   /home/alex/Build/dlib/dlib_git/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/../optimization/optimization_line_search.h:211:61:   required from here
   ***   /home/alex/Build/dlib/dlib_git/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h:1783:14: error: cannot call member function ‘long int dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::nr() const [with T = double; long int num_rows = 2; long int num_cols = 1; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’ without object
   ***                    DLIB_CASSERT(r < m->nr() && c < m->nc(),
   ***                 ^  ~~~~
   ***   /home/alex/Build/dlib/dlib_git/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h:1783:30: error: cannot call member function ‘long int dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::nc() const [with T = double; long int num_rows = 2; long int num_cols = 1; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’ without object
   ***                    DLIB_CASSERT(r < m->nr() && c < m->nc(),
   ***                            ~~~~~^~~~~~~
   ***   /home/alex/Build/dlib/dlib_git/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h:1783:890: error: cannot call member function ‘long int dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::nr() const [with T = double; long int num_rows = 2; long int num_cols = 1; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’ without object
   ***                    DLIB_CASSERT(r < m->nr() && c < m->nc(),
   ***                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^          
   ***   /home/alex/Build/dlib/dlib_git/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/matrix.h:1783:926: error: cannot call member function ‘long int dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::nc() const [with T = double; long int num_rows = 2; long int num_cols = 1; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’ without object
   ***                    DLIB_CASSERT(r < m->nr() && c < m->nc(),
   ***                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^          
   ***   CMake Error at cuda_test_generated_cuda_test.cu.o.cmake:275 (message):
   ***     Error generating file
   ***     /home/alex/Build/dlib/dlib_git/build/dlib/cuda_test_build/CMakeFiles/cuda_test.dir//./cuda_test_generated_cuda_test.cu.o
   ***   
   ***   
   ***   gmake[2]: *** [CMakeFiles/cuda_test.dir/build.make:65: CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o] Error 1
   ***   gmake[1]: *** [CMakeFiles/Makefile2:72: CMakeFiles/cuda_test.dir/all] Error 2
   ***   gmake: *** [Makefile:84: all] Error 2
   ***   
-- *****************************************************************************************************************
-- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
-- C++11 activated.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/alex/Build/dlib/dlib_git/build
```

## Steps to Reproduce
<!--- Provide an unambiguous set of steps to reproduce this problem.  What exactly do I have to type to reproduce your error?  If you don't post complete instructions you are much less likely to get help. -->
- Git clone dlib and cd into the project.
- `mkdir build && cd build`
- `cmake ..`

* **Version**: <!-- What version of dlib? -->
Git HEAD 70f9a9f11fb2ae82a057e5f4b3bae9238087e418 

* **Where did you get dlib**: <!-- Did you get it from an official source like dlib.net, this github repo, or somewhere else? -->
Github.

* **Platform**: <!-- include something like `lsb_release -a` output, or if Windows, version and 32-bit or
  64-bit -->
```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 29 (Twenty Nine)
Release:	29
Codename:	TwentyNine
$ uname -a
Linux REDACTED 4.19.12-301.fc29.x86_64 #1 SMP Mon Dec 24 01:58:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

* **Compiler**: <!-- What compiler are you using?  What version of that compiler? -->
gcc (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)

**Comment by alexmarkley** [comment]
The following patch allowed the test program to compile successfully:

```
diff --git a/dlib/matrix/matrix.h b/dlib/matrix/matrix.h
index 224affb6..cdfbe891 100644
--- a/dlib/matrix/matrix.h
+++ b/dlib/matrix/matrix.h
@@ -1771,7 +1771,7 @@ namespace dlib
             explicit literal_assign_helper(matrix* m_): m(m_), r(0), c(0),has_been_used(false) {next();}
             ~literal_assign_helper() noexcept(false)
             {
-                DLIB_CASSERT(!has_been_used || r == m->nr(),
+                DLIB_CASSERT(!has_been_used || r == (*m).nr(),
                              "You have used the matrix comma based assignment incorrectly by failing to\n"
                              "supply a full set of values for every element of a matrix object.\n");
             }
@@ -1780,14 +1780,14 @@ namespace dlib
                 const T& val
             ) const
             {
-                DLIB_CASSERT(r < m->nr() && c < m->nc(),
+                DLIB_CASSERT(r < (*m).nr() && c < (*m).nc(),
                              "You have used the matrix comma based assignment incorrectly by attempting to\n" <<
                              "supply more values than there are elements in the matrix object being assigned to.\n\n" <<
                              "Did you forget to call set_size()?" 
                              << "\n\t r: " << r 
                              << "\n\t c: " << c 
-                             << "\n\t m->nr(): " << m->nr()
-                             << "\n\t m->nc(): " << m->nc());
+                             << "\n\t m->nr(): " << (*m).nr()
+                             << "\n\t m->nc(): " << (*m).nc());
                 (*m)(r,c) = val;
                 next();
                 has_been_used = true;
@@ -1802,7 +1802,7 @@ namespace dlib
             ) const
             {
                 ++c;
-                if (c == m->nc())
+                if (c == (*m).nc())
                 {
                     c = 0;
                     ++r;
```

I don't know if this is some GCC 8 weirdness or what. We'll see if the patch works or if this just makes everything worse.

**Comment by alexmarkley** [comment]
It worked. The patch I created [above](https://github.com/davisking/dlib/issues/1676#issuecomment-468957540) allowed me to successfully compile and install Dlib. I've also tested it with my workload and it appears to be working.

**Comment by daisyron** [comment]
Tried it and it worked for me as well :-)

**Comment by alexmarkley** [comment]
Sorry to spam the issue, but I was able to reproduce the same problem on another system:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
$ uname -a
Linux REDACTED 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ gcc --version
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

My patch worked for this system as well.

**Comment by yuaowang** [comment]
WOW, it worked for my system! Cheers.

**Comment by davisking** [comment]
@alexmarkley wow, that's a weird compiler bug.  Thanks for figuring it out :)  Do you want to submit a PR for it?

**Comment by qc2105** [comment]
Solved my problem too. Thanks!

**Comment by pavelpe** [comment]
> I just tried cuda 10.1 and the only issue I found was on some versions of cmake it doesn't find cusolver. I just pushed a fix for that, but I didn't see any other issues. There is probably just something wrong with your cuda install unrelated to dlib.
> 

This solved my recent dlib setup problem  (since last Thursday). 
Just to for the record my platform:

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Code name: xenial
CMake version: 3.5.1
dlib version: 19.16.99
cuda version: cuda-10.1
g++ (Ubuntu 5.4.0-6ubuntu1~16.04) 5.4.0

**Comment by davisking** [comment]
Thanks everyone for reporting this.  I just pushed the fix into master on github. I've also been able to reproduce this myself, although only on Ubuntu 18.04.  Oddly never able to reproduce it on Ubuntu 16.04.  But in any case, it should be fixed now.

**Comment by Christianwidjaya** [comment]
just wanna to help, cmake version 3.14 rc2 solved this for me, it seems cmake 3.12 doesn't recognize cuda 10.1

**Comment by pnzr00t** [comment]
> just wanna to help, cmake version 3.14 rc2 solved this for me, it seems cmake 3.12 doesn't recognize cuda 10.1
Try 
> Using CMake version: 3.16.8
But problem not solved :(
