### ISSUE TITLE
Cuda 10.1 cusolver CMake issue

### ISSUE THREAD

**Issue by daisyron** [davisking/dlib#1678]
Hi,

Trying to compile dlib (current clone of master) under Centos 7, failed to find cusolver (even though I have the correction make to solve this issue).

cmake output snippet:

..........
-- Found CUDA: /usr/local/cuda (found suitable version "10.1", minimum required is "7.5") 
-- Looking for cuDNN install...
-- Found cuDNN: /usr/local/cuda/lib64/libcudnn.so
-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- Checking if you have the right version of cuDNN installed.
-- Enabling CUDA support for dlib.  DLIB WILL USE CUDA
-- C++11 activated.
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cusolver_LIBRARY (ADVANCED)
    linked by target "dlib" in directory /home/ron/DeepLearning/dlib/dlib

-- Configuring incomplete, errors occurred!
See also "/home/ron/DeepLearning/dlib/build/CMakeFiles/CMakeOutput.log".
See also "/home/ron/DeepLearning/dlib/build/CMakeFiles/CMakeError.log".
========================

My configuration:

dlib: clean master. git log:
commit 663a1b712781846e1c4592ac2715a6276317095a
Author: Davis King <davis@dlib.net>
Date:   Sun Mar 3 21:35:15 2019 -0500

OS: Linux Centos 7 64 bits.
cmake: 2.8.12.2
gcc: 4.8.5 20150623 (Red Hat 4.8.5-16)
Cuda: 10.1

Regards,
Ron.

**Comment by ccl-private** [comment]
Cuda 10.1 may not perfectly support yet. Recommend use Cuda 9.0 instead. I install Cuda 9.0 alongside Cuda 10.1, which can be switched at any time. One more thing to pay attention to is the version of gcc and g++. Cuda 9.0 need 6th version, also I recommend install both 6th version and 7th version in an easy switching way.

I solved my problem inspired by this issue:
https://github.com/davisking/dlib/issues/1439

**Comment by davisking** [comment]
CUDA 10.0 works fine, 10.1 however seems to be missing symbolic links to libcusolver.so, which is the root of the issue.  Newer versions of cmake still find it with the fix I added the other day.

You should look at where libcusolver.so is located and add that path to the HINTS in CMakeLists.txt where it's searching for it.  Maybe that's a sensible workaround for this issue.  That is, just adding more folders to the search list.

**Comment by daisyron** [comment]
Thank for your help... used newer version of cmake and successfully
compiled it.

**Comment by ZHUchaojun** [comment]
@daisyron  I have same problem, but I have more varibles unknow, such as:
CUDA_cublas_LIBRARY
CUDA_curand_LIBRARY
CUDA_cusolver_LIBRARY

And I use docker image is base tensorflow-gpu, and cmake is 3.5.1 , cuda is 9.0, cudnn is 7.1. 

I also try to use cmake3.14.6, but no use, I want to know what cmake version are you used? Thank you

**Comment by CyanideCentral** [comment]
I got a similar error while trying to compile dlib from source, with CMake 3.16.3, Cuda 10.0 and CuDNN 7.6.5. The error message is: 

> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_curand_LIBRARY (ADVANCED)
linked by target "dlib" in directory /home/ron/DeepLearning/dlib/dlib
CUDA_cusolver_LIBRARY (ADVANCED)
linked by target "dlib" in directory /home/ron/DeepLearning/dlib/dlib

It was because CMake could not find the .so files for these two libraries under /usr/local/cuda/lib64, and that header file 'cusolverDn.h' is missing. In my case, libcurand and libcusolver can be properly installed by running these commands:
`apt-get install cuda-cusolver-dev-10-0`
`apt-get install cuda-curand-dev-10-0`
"10-0" should be adjusted based on specific Cuda version. Alternatively, install the corresponding libraries from [Nvidia website](https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64/).

**Comment by Himeshi** [comment]
Had the same issue with cuda-10.1 but adding the hint worked.

`find_library(cusolver cusolver HINTS "/usr/local/cuda-10.1/targets/x86_64-linux/lib/")`
