### ISSUE TITLE
CUDA Runtime API initialization failed

### ISSUE THREAD

**Issue by mv2050arshad** [davisking/dlib#2113]
Hi.
When i running any api from Dlib, i get this error : "CUDA Runtime API initialization failed"

cuda 9.1
cudnn 7.1.3
graphic driver 391

any idea ?

**Comment by davisking** [comment]
Something is wrong with your CUDA install.  That's not a dlib error.  It's
an error from the CUDA runtime telling you CUDA isn't installed correctly,
your driver isn't right, or something like that.

**Comment by krzesu0** [comment]
I just fixed the same issue. Try using libraries designated for the same version of CUDA (`libcudnn7`, `-dev` and whole toolkit, all for the CUDA 10). It looks like a version mismatch or something.

**Comment by mv2050arshad** [comment]
thanks for your answer guys.
you know that error happen only in python , when i used c++ evey thing run well.

**Comment by facug91** [comment]
I'm having the same error. I was using this nvidia docke image [nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04](https://hub.docker.com/layers/nvidia/cuda/10.0-cudnn7-devel-ubuntu18.04/images/sha256-e277b9eef79d6995b10d07e30228daa9e7d42f49bcfc29d512c1534b42d91841?context=explore). Now I changed to [10.2-cudnn8-devel-ubuntu18.04](https://hub.docker.com/layers/nvidia/cuda/10.2-cudnn8-devel-ubuntu18.04/images/sha256-c1652dcb648182129a50a610e39173ff5f2316aafb236a237cf66fbbd36b032e?context=explore), and I'm getting this error. In this case I'm using the installation provided by Nvidia, so I don't know what's the problem.  
By the way, I'm using dlib's master branch.

**Comment by facug91** [comment]
Well, I've found the problem. It seems that if I perform an `apt-get upgrade`, the cuDNN library is update to use CUDA 11, and that's why this error arise. I removed the upgrade from the Dockerfile and it's working now.
