### ISSUE TITLE
CuDNN error on Jetson Nano :: "reason: CUDNN_STATUS_NOT_SUPPORTED"

### ISSUE THREAD

**Issue by SIGMIND** [davisking/dlib#2330]
I am using Dlib 19.21 on Jetson Nano on a project. But running a program causes a strange CUDNN error wheres the program was running fine on previous L4T 32.4 version. My Jetson Nano software stacks are like this:

```
    NVIDIA Jetson Nano
     L4T 32.5.0 [ JetPack UNKNOWN ]
       Ubuntu 18.04.5 LTS
       Kernel Version: 4.9.201-tegra
     CUDA 10.2.89
       CUDA Architecture: 5.3
     OpenCV version: 4.1.1
       OpenCV Cuda: NO
     CUDNN: 8.0.0.180
     TensorRT: 7.1.3.0
     Vision Works: 1.6.0.501
     VPI: ii libnvvpi1 1.0.12 arm64 NVIDIA Vision Programming Interface library
```

But its causing error like this:

```
terminate called after throwing an instance of 'dlib::cudnn_error'
 what():  Error while calling cudnnGetConvolutionBackwardFilterWorkspaceSize( context(), descriptor(data), descriptor(dest_desc), (const cudnnConvolutionDescriptor_t)conv_handle, (const cudnnFilterDescriptor_t)filter_handle, (cudnnConvolutionBwdFilterAlgo_t)backward_filters_algo, &backward_filters_workspace_size_in_bytes) in file /home/nvidia/dlib/dlib/cuda/cudnn_dlibapi.cpp:1046. code: 9, reason: CUDNN_STATUS_NOT_SUPPORTED
```

**Comment by zneel** [comment]
Hello, I have the same issue using https://github.com/ageitgey/face_recognition
```
Error while calling cudnnGetConvolutionBackwardFilterWorkspaceSize( context(), descriptor(data), descriptor(dest_desc), (const cudnnConvolutionDescriptor_t)conv_handle, (const cudnnFilterDescriptor_t)filter_handle, (cudnnConvolutionBwdFilterAlgo_t)backward_filters_algo, &backward_filters_workspace_size_in_bytes) in file /home/zneel/workspace/dlib/dlib/cuda/cudnn_dlibapi.cpp:1039. code: 9, reason: CUDNN_STATUS_NOT_SUPPORTED
```

```
CUDA Version 11.0.228
libcudnn8=8.1.1.33-1+cuda11.2 amd64 [installed]
libcudnn8-dev=8.1.1.33-1+cuda11.2 amd64 [installed]
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

**Comment by MustafaSmesem** [comment]
same for me when using multi-gpu or initialize alot of threads in the same time

terminate called after throwing an instance of 'dlib::cudnn_error'
  what():  Error while calling cudnnFindConvolutionForwardAlgorithm( context(), descriptor(data), (const cudnnFilterDescriptor_t)filter_handle, (const cudnnConvolutionDescriptor_t)conv_handle, descriptor(dest_desc), num_possible_algorithms, &num_algorithms, perf_results.data()) in file /home/spookRemote/3rdparty/dlib/dlib/cuda/cudnn_dlibapi.cpp:820. code: 4, reason: A call to cuDNN failed
  
CUDA Version 11.2
libcudnn8=8.1.1.33-1+cuda11.2 amd64 [installed]
libcudnn8-dev=8.1.1.33-1+cuda11.2 amd64 [installed]
dlib version: 19.21.99
CMake version: 3.12.3
GPU 2X NIVIDIA Tesla P40

**Comment by MustafaSmesem** [comment]
I found what going wrong for me, I have started a lot of threads for processing one video and set each thread to a different Cuda device. So it sometimes works fine and sometimes get's the previous Cudnn error.
when I stop switching the devices the problem is disappeared.

**Comment by fatalfeel** [comment]
this is cudnn and driver not match problem
Do this will solved:
driver: NVIDIA-Linux-x86_64-440.118.02.run (Product Type: Data Center)
cuda: cuda_10.2.89_440.33.01_linux.run (uncheck default driver install)
cuda patch 1: cuda_10.2.1_linux.run
cuda patch 2: cuda_10.2.2_linux.run
libcudnn: (using 7.6.5 will cause Error while calling cudnnConvolutionBiasActivationForward)
libcudnn8_8.0.5.39-1+cuda10.2_amd64.deb
libcudnn8-dev_8.0.5.39-1+cuda10.2_amd64.deb
libcudnn8-samples_8.0.5.39-1+cuda10.2_amd64.deb
