### ISSUE TITLE
Dlib cnn detector failing with  code: 600, reason: device not ready

### ISSUE THREAD

**Issue by aimanuslim** [davisking/dlib#2451]
## Expected Behavior

I was running the code located [here ](https://github.com/csxmli2016/DFDNet/blob/whole/test_FaceDict.py)and it reached to the part where it tries to use the cnn detector and breaks due to error below.
I expected that image detector for cnn_face_detection_model_v1() should work properly and use the GPU as expected. I tested using a CPU dlib version of this, and it worked, but was painfully slow.

## Current Behavior

detector code is breaking

```
  File "test_FaceDict.py", line 26, in get_5_points
    dets = detector(img, 1)
RuntimeError: Error while calling err in file C:\Users\User\AppData\Local\Temp\pip-install-72q7pmts\dlib_19599fc305d04f0daf10d17aee4187d0\dlib\cuda\gpu_data.cpp:100.
 code: 600, reason: device not ready
```
I had made sure that GPU is not being used or at high usage when running it.

## Steps to Reproduce

Install dlib using `pip install dlib`

run this code
```
detector = dlib.cnn_face_detection_model_v1('./packages/mmod_human_face_detector.dat')
img = dlib.load_rgb_image(img_path)
dets = detector(img, 1) 
```
System Information:
Windows Version	10.0.19042 Build 19042
GPU RTX A4000
CPU Ryzen 3950x

Also,

`dlib.DLIB_USE_CUDA` returns `True`

* **DLIB Version**:   19.22.0
* **Where did you get dlib**:  pip install (pypi)
* **Platform**:  64 bit windows,
* **Compiler**:  During pip install, it does not mention which visual studio build tools it was using, but I believed it was `Visual Studio 15 2017` since it was failing before I tried installing it, and then when I installed `Visual Studio 15 2017` it worked.

Code was executed on Anaconda Powershell prompt if that matters.

**Comment by aimanuslim** [comment]
I rechecked my CUDA_PATH and PATH pointers, tried python setup.py install on repo and make sure it picks up the correct cudnn, but then used pip install dlib with all of that done. 

Seems to be working now with cudatoolkit 11.3 and cudnn 11.x July 2021.

P/S: python  setup.py install fails with this error: 


```
copying tools\python\dlib.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying tools\python\dlib.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying tools\python\dlib.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying tools\python\dlib.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
copying tools\python\dlib.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
error: [WinError 183] Cannot create a file when that file already exists: 'build\\bdist.win-amd64\\egg\\EGG-INFO\\PKG-INFO'
```
