### ISSUE TITLE
Example :  dnn_mmod_ex.cpp  runs error

### ISSUE THREAD

**Issue by blackwool** [davisking/dlib#429]
Thank you for the great job!  I like dlib.
I compile this  example and run ,it throws exception  as :
     Microsoft C++ Exception : dlib::cuda_error，in  0x0000007AC90FE870  。

below is my  compile environment :
os         :  windows10
cuda     :  ver 8.0
cudnn   :  ver5.0
compiler:  Microsoft Visual Studio14.0  c/c++ 19.00.24215.1
build ver:  x64  release

I  trace  and find it happens  in "train.h"  bellow

void send_job (
            data_iterator dbegin, 
            data_iterator dend,
            label_iterator lbegin
        )
        {
            propagate_exception();   //this line throw error, after this function is called 2 times later

I try to skip this line  ,this example runs ok, but the result seems not right,
after 5 hours ,it still report as below，and not end yet.

step #   0    learning rate:0.1 average loss: 0      steps without apparent  progress:0
.......
 step# 22500 learning rate:0.1 average loss: 0      steps without apparent  progress:0

Is there anything wrong ? 

Look forward to your favourable reply .

**Comment by davisking** [comment]
Exceptions have error messages in them.  Moreover, the example includes code that prints the message to the screen.  You should read the error message.

**Comment by blackwool** [comment]
Hi Davisking:
The error occurs at "gpu_data.cpp" lines 201 : cudaerror: out or memory
    CHECK_CUDA(cudaMalloc(&data, new_size*sizeof(float)));

I change the " mini_batch_samples" size from 150 to 32. and the example runs ok.
 thank you  very much.

**Comment by blackwool** [comment]
Hi Davisking:
the network is trained,and the dnn_mmod_ex.cpp runs ok. thank you.
but when i use this network in dnn_mmod_face_detection_ex.cpp, the program report error( cudaerror,out of memory) when detect  face\2009_004587.bmp. my computer have 2G Gpu memory.Do you encount this problem?

**Comment by mkisono** [comment]
I had a similar issue on my environment which has only 1GB of GPU memory.
It worked for me after I modified the code to call pyramid_up() only once.

```
        // while(img.size() < 1000*1000)
        pyramid_up(img);
```
