### ISSUE TITLE
Can't run the example dnn_mmod_face_detection_ex

### ISSUE THREAD

**Issue by peterpans01** [davisking/dlib#457]
Hello, 
     I installed dlib without any problem (linked to cuda, cudnn,...). So i tried to use the pretrained model to test on some images: 
   ./dnn_mmod_face_detection_ex mmod_human_face_detector.dat dlib-19.3/examples/faces/2008_004176.jpg

I used CUDA 8.0 and CUDNN 5.1.

The problem is I always get this error: 

Error while calling cudnnSetFilter4dDescriptor((cudnnFilterDescriptor_t)filter_handle, CUDNN_DATA_FLOAT, CUDNN_TENSOR_NCHW, filters.num_samples(), filters.k(), filters.nr(), filters.nc()) in file dlib-19.3/dlib/dnn/cudnn_dlibapi.cpp:822. code: 3, reason: CUDNN_STATUS_BAD_PARAM

Could you help me where did I do wrong?

**Comment by davisking** [comment]
You shouldn't get that error.  There is probably something wrong with your CUDA install.  I would reinstall CUDA and cuDNN.

**Comment by peterpans01** [comment]
Thanks for your support. I found the problem. Dlib linked to wrong cudnn version. In our system contains both versions of cudnn for cuda 7.5 and  cuda 8.0. It actually linked to 7.5. I still don't know why. After corrected it, it works.

**Comment by ncuxiaogang** [comment]
@peterpans01 I met the same problem, I used CUDA 8.0 and CUDNN 6.0. But I do not know how to slove the problem? Thanks.
