### ISSUE TITLE
no CUDA-capable device is detected

### ISSUE THREAD

**Issue by pencoa** [davisking/dlib#499]
While I using tensorflow, it can detect cuda device.
While I using dlib dnn_mmod_ex, there is one error aroused.
`Error while calling cudaGetDevice(&dev) in file /home/randy/dlib/dlib/dnn/cuda_dlib.cu:26. code: 38, reason: no CUDA-capable device is detected`
![screenshot from 2017-03-23 11-27-32](https://cloud.githubusercontent.com/assets/7123063/24230871/56a14fd6-0fbc-11e7-81c7-36b37da26386.png)
And I try to reinstall cuda via package manager. It seems that all is installed.
![screenshot from 2017-03-23 11-28-41](https://cloud.githubusercontent.com/assets/7123063/24230880/673b63b8-0fbc-11e7-8b0c-4c0d73d07866.png)
![screenshot from 2017-03-23 11-28-56](https://cloud.githubusercontent.com/assets/7123063/24230882/6e15c336-0fbc-11e7-9ce7-e75751ea0d9c.png)

**Comment by e-fominov** [comment]
Your libraries are compiled and that means that compilation is successfull, it does not mean it will run well.
Running Dlib with CUDA support enable requires Nvidia GPU with Kepler or newer architecture (CUDA device compute compatibility 3+). It will not work on AMD/Intel/other gpu/without gpu or with old Nvidia cards
If you do not have compatible GPU on your machine, you should recompile Dlib without CUDA support and work with CPU mode or you can run your binaries on other machine...

**Comment by davisking** [comment]
Your GPU is too old.  I should point out that the requirements for CUDA compute capability 3.0 or newer, which your card does not satisfy because it's too old, are requirements from cuDNN.  So this isn't a dlib issue. Anything that uses cuDNN needs newer hardware.  Here is the relevant documentation from cuDNN's manual:

```
cuDNN v5.1 supports NVIDIA GPUs of compute capability 3.0 and higher and requires
an NVIDIA Driver compatible with CUDA Toolkit 7.5 (CUDA Toolkit 7.0 for ARM
platforms).
```

So I don't know what tensorflow is doing.  It probably silently disables cuDNN.

**Comment by smajida** [comment]
I have a pretty new GPU: Titan X (Pascal) with CUDA 8, but I am getting the same error:
@davisking @e-fominov @pencoa 
```bash
    face_encoder = dlib.face_recognition_model_v1(face_recognition_model)
RuntimeError: Error while calling cudaGetDevice(&the_device_id) in file /tmp/pip-build-dls8jvxk/dlib/dlib/dnn/gpu_data.cpp:178. code: 38, reason: no CUDA-capable device is detected
```
```bash
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```

**Comment by e-fominov** [comment]
This should be a problem with hardware or drivers 

Check the output of **nvidia-smi** command line tool
For Pascal I can recommend to use driver version 381

**Comment by smajida** [comment]
thanks.

**Comment by ypflll** [comment]
Also meet this problem, and seems that this only happens when I try to use dlib in python:

> RuntimeError: Error while calling cudaGetDevice(&the_device_id) in file /home/yaopengfei/Desktop/dlib-19.10.0/dlib/dnn/gpu_data.cpp:178. code: 38, reason: no CUDA-capable device is detected

Output of nvidia-smi:
![image](https://user-images.githubusercontent.com/12528364/39987926-a2adee64-5798-11e8-9d09-a32aff727acd.png)

Other  program using tensorflow or caffe runs well, so I don't think it's a problem of gpu driver.
This really confuses me. @smajida How do you solve it?
@e-fominov  Is there other thing I need to check when using dlib?

**Comment by Shweta1127** [comment]
Same kind of problem happen but solved thanks.

**Comment by murugan-bala** [comment]
> thanks. It solved the problem. It was a problem of paths as as usual :(

how can u solved..pls help me out

**Comment by murugan-bala** [comment]
> Same kind of problem happen but solved thanks.

how can u solved..pls help me out

**Comment by luhuawxb** [comment]
Try this before import face_recognition:
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]= "0"

![UF8IOJ}IG5(K8 NIY8{H0BC](https://user-images.githubusercontent.com/46490575/114643959-3686c300-9d09-11eb-9921-fed21e4fc4e9.png)
perfect to be solved.
